services:

  db:
    image: postgres:16
    container_name: odoo-formation-db

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo

    volumes:
      - odoo_formation_postgres:/var/lib/postgresql/data

    restart: always


  odoo:
    image: odoo:19
    container_name: odoo-formation-web

    depends_on:
      - db

    ports:
      - "8069:8069"

    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo

    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - odoo_formation_data:/var/lib/odoo

    restart: always


volumes:

  odoo_formation_postgres:

  odoo_formation_data: